# Site settings
title: Scador.com
email: scador@scador.com
description: > # this means to ignore newlines until "baseurl:"
  Scador MC is new approach to Configure Price Quote - it helps to encapsulate expert 
  knowledge about product and renders consumer ready configurator application supporting 
  pricing and quoting process of sale. Our goal is to integrate well with manufacturing lanes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.scador.com" # the base hostname & protocol for your site
#twitter_username: scador
#github_username:  scador-mc
safe: false

# Build settings
markdown: kramdown

